version: '3.8'
services: 
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        command: npm run start
        container_name: frontend
        ports:
          - "3000:3000"        
        volumes: 
          - ./frontend:/frontend
          - /frontend/node_modules
        environment:
          - CHOKIDAR_USEPOLLING=true
    web:
      build: ./app
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./app/:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./.env.dev
