version: '3.8'
services: 
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        command: npm run start
        container_name: frontend
        ports:
          - "3000:3000"        
        volumes: 
          - ./frontend:/frontend
          - /frontend/node_modules
        environment:
          - CHOKIDAR_USEPOLLING=true
