# Generated by Django 4.0.4 on 2022-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=6)),
                ('stock_quantity', models.IntegerField()),
                ('avg_cost', models.FloatField()),
                ('trade_date', models.DateField()),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255)),
            ],
        ),
    ]
